// source: injective/insurance/v1beta1/insurance.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var cosmos_base_v1beta1_coin_pb = require('../../../cosmos/base/v1beta1/coin_pb.js');
goog.object.extend(proto, cosmos_base_v1beta1_coin_pb);
var injective_oracle_v1beta1_oracle_pb = require('../../../injective/oracle/v1beta1/oracle_pb.js');
goog.object.extend(proto, injective_oracle_v1beta1_oracle_pb);
goog.exportSymbol('proto.injective.insurance.v1beta1.EventInsuranceFundUpdate', null, global);
goog.exportSymbol('proto.injective.insurance.v1beta1.EventRequestRedemption', null, global);
goog.exportSymbol('proto.injective.insurance.v1beta1.EventWithdrawRedemption', null, global);
goog.exportSymbol('proto.injective.insurance.v1beta1.InsuranceFund', null, global);
goog.exportSymbol('proto.injective.insurance.v1beta1.Params', null, global);
goog.exportSymbol('proto.injective.insurance.v1beta1.RedemptionSchedule', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.injective.insurance.v1beta1.Params = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.injective.insurance.v1beta1.Params, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.injective.insurance.v1beta1.Params.displayName = 'proto.injective.insurance.v1beta1.Params';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.injective.insurance.v1beta1.InsuranceFund = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.injective.insurance.v1beta1.InsuranceFund, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.injective.insurance.v1beta1.InsuranceFund.displayName = 'proto.injective.insurance.v1beta1.InsuranceFund';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.injective.insurance.v1beta1.RedemptionSchedule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.injective.insurance.v1beta1.RedemptionSchedule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.injective.insurance.v1beta1.RedemptionSchedule.displayName = 'proto.injective.insurance.v1beta1.RedemptionSchedule';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.injective.insurance.v1beta1.EventInsuranceFundUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.displayName = 'proto.injective.insurance.v1beta1.EventInsuranceFundUpdate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.injective.insurance.v1beta1.EventRequestRedemption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.injective.insurance.v1beta1.EventRequestRedemption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.injective.insurance.v1beta1.EventRequestRedemption.displayName = 'proto.injective.insurance.v1beta1.EventRequestRedemption';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.injective.insurance.v1beta1.EventWithdrawRedemption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.injective.insurance.v1beta1.EventWithdrawRedemption.displayName = 'proto.injective.insurance.v1beta1.EventWithdrawRedemption';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.injective.insurance.v1beta1.Params.prototype.toObject = function(opt_includeInstance) {
  return proto.injective.insurance.v1beta1.Params.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.injective.insurance.v1beta1.Params} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.Params.toObject = function(includeInstance, msg) {
  var f, obj = {
    defaultRedemptionNoticePeriodDuration: (f = msg.getDefaultRedemptionNoticePeriodDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.injective.insurance.v1beta1.Params}
 */
proto.injective.insurance.v1beta1.Params.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.injective.insurance.v1beta1.Params;
  return proto.injective.insurance.v1beta1.Params.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.injective.insurance.v1beta1.Params} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.injective.insurance.v1beta1.Params}
 */
proto.injective.insurance.v1beta1.Params.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setDefaultRedemptionNoticePeriodDuration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.injective.insurance.v1beta1.Params.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.injective.insurance.v1beta1.Params.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.injective.insurance.v1beta1.Params} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.Params.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDefaultRedemptionNoticePeriodDuration();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Duration default_redemption_notice_period_duration = 1;
 * @return {?proto.google.protobuf.Duration}
 */
proto.injective.insurance.v1beta1.Params.prototype.getDefaultRedemptionNoticePeriodDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 1));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.injective.insurance.v1beta1.Params} returns this
*/
proto.injective.insurance.v1beta1.Params.prototype.setDefaultRedemptionNoticePeriodDuration = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.injective.insurance.v1beta1.Params} returns this
 */
proto.injective.insurance.v1beta1.Params.prototype.clearDefaultRedemptionNoticePeriodDuration = function() {
  return this.setDefaultRedemptionNoticePeriodDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.injective.insurance.v1beta1.Params.prototype.hasDefaultRedemptionNoticePeriodDuration = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.toObject = function(opt_includeInstance) {
  return proto.injective.insurance.v1beta1.InsuranceFund.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.injective.insurance.v1beta1.InsuranceFund} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.InsuranceFund.toObject = function(includeInstance, msg) {
  var f, obj = {
    depositDenom: jspb.Message.getFieldWithDefault(msg, 1, ""),
    insurancePoolTokenDenom: jspb.Message.getFieldWithDefault(msg, 2, ""),
    redemptionNoticePeriodDuration: (f = msg.getRedemptionNoticePeriodDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    balance: jspb.Message.getFieldWithDefault(msg, 4, ""),
    totalShare: jspb.Message.getFieldWithDefault(msg, 5, ""),
    marketId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    marketTicker: jspb.Message.getFieldWithDefault(msg, 7, ""),
    oracleBase: jspb.Message.getFieldWithDefault(msg, 8, ""),
    oracleQuote: jspb.Message.getFieldWithDefault(msg, 9, ""),
    oracleType: jspb.Message.getFieldWithDefault(msg, 10, 0),
    expiry: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund}
 */
proto.injective.insurance.v1beta1.InsuranceFund.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.injective.insurance.v1beta1.InsuranceFund;
  return proto.injective.insurance.v1beta1.InsuranceFund.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.injective.insurance.v1beta1.InsuranceFund} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund}
 */
proto.injective.insurance.v1beta1.InsuranceFund.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDepositDenom(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInsurancePoolTokenDenom(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRedemptionNoticePeriodDuration(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBalance(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTotalShare(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarketId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarketTicker(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setOracleBase(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setOracleQuote(value);
      break;
    case 10:
      var value = /** @type {!proto.injective.oracle.v1beta1.OracleType} */ (reader.readEnum());
      msg.setOracleType(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpiry(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.injective.insurance.v1beta1.InsuranceFund.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.injective.insurance.v1beta1.InsuranceFund} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.InsuranceFund.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDepositDenom();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInsurancePoolTokenDenom();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRedemptionNoticePeriodDuration();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getBalance();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTotalShare();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMarketId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMarketTicker();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getOracleBase();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getOracleQuote();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getOracleType();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = message.getExpiry();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
};


/**
 * optional string deposit_denom = 1;
 * @return {string}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getDepositDenom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setDepositDenom = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string insurance_pool_token_denom = 2;
 * @return {string}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getInsurancePoolTokenDenom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setInsurancePoolTokenDenom = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Duration redemption_notice_period_duration = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getRedemptionNoticePeriodDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
*/
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setRedemptionNoticePeriodDuration = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.clearRedemptionNoticePeriodDuration = function() {
  return this.setRedemptionNoticePeriodDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.hasRedemptionNoticePeriodDuration = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string balance = 4;
 * @return {string}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getBalance = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setBalance = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string total_share = 5;
 * @return {string}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getTotalShare = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setTotalShare = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string market_id = 6;
 * @return {string}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getMarketId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setMarketId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string market_ticker = 7;
 * @return {string}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getMarketTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setMarketTicker = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string oracle_base = 8;
 * @return {string}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getOracleBase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setOracleBase = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string oracle_quote = 9;
 * @return {string}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getOracleQuote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setOracleQuote = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional injective.oracle.v1beta1.OracleType oracle_type = 10;
 * @return {!proto.injective.oracle.v1beta1.OracleType}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getOracleType = function() {
  return /** @type {!proto.injective.oracle.v1beta1.OracleType} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {!proto.injective.oracle.v1beta1.OracleType} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setOracleType = function(value) {
  return jspb.Message.setProto3EnumField(this, 10, value);
};


/**
 * optional int64 expiry = 11;
 * @return {number}
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.getExpiry = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.injective.insurance.v1beta1.InsuranceFund} returns this
 */
proto.injective.insurance.v1beta1.InsuranceFund.prototype.setExpiry = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.toObject = function(opt_includeInstance) {
  return proto.injective.insurance.v1beta1.RedemptionSchedule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.injective.insurance.v1beta1.RedemptionSchedule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    marketid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    redeemer: jspb.Message.getFieldWithDefault(msg, 3, ""),
    claimableRedemptionTime: (f = msg.getClaimableRedemptionTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    redemptionAmount: (f = msg.getRedemptionAmount()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.injective.insurance.v1beta1.RedemptionSchedule}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.injective.insurance.v1beta1.RedemptionSchedule;
  return proto.injective.insurance.v1beta1.RedemptionSchedule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.injective.insurance.v1beta1.RedemptionSchedule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.injective.insurance.v1beta1.RedemptionSchedule}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarketid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedeemer(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setClaimableRedemptionTime(value);
      break;
    case 5:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setRedemptionAmount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.injective.insurance.v1beta1.RedemptionSchedule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.injective.insurance.v1beta1.RedemptionSchedule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getMarketid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRedeemer();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getClaimableRedemptionTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getRedemptionAmount();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.injective.insurance.v1beta1.RedemptionSchedule} returns this
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string marketId = 2;
 * @return {string}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.getMarketid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.RedemptionSchedule} returns this
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.setMarketid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string redeemer = 3;
 * @return {string}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.getRedeemer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.injective.insurance.v1beta1.RedemptionSchedule} returns this
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.setRedeemer = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp claimable_redemption_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.getClaimableRedemptionTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.injective.insurance.v1beta1.RedemptionSchedule} returns this
*/
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.setClaimableRedemptionTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.injective.insurance.v1beta1.RedemptionSchedule} returns this
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.clearClaimableRedemptionTime = function() {
  return this.setClaimableRedemptionTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.hasClaimableRedemptionTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional cosmos.base.v1beta1.Coin redemption_amount = 5;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.getRedemptionAmount = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 5));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.injective.insurance.v1beta1.RedemptionSchedule} returns this
*/
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.setRedemptionAmount = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.injective.insurance.v1beta1.RedemptionSchedule} returns this
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.clearRedemptionAmount = function() {
  return this.setRedemptionAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.injective.insurance.v1beta1.RedemptionSchedule.prototype.hasRedemptionAmount = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.injective.insurance.v1beta1.EventInsuranceFundUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    fund: (f = msg.getFund()) && proto.injective.insurance.v1beta1.InsuranceFund.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.injective.insurance.v1beta1.EventInsuranceFundUpdate}
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.injective.insurance.v1beta1.EventInsuranceFundUpdate;
  return proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.injective.insurance.v1beta1.EventInsuranceFundUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.injective.insurance.v1beta1.EventInsuranceFundUpdate}
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.injective.insurance.v1beta1.InsuranceFund;
      reader.readMessage(value,proto.injective.insurance.v1beta1.InsuranceFund.deserializeBinaryFromReader);
      msg.setFund(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.injective.insurance.v1beta1.EventInsuranceFundUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFund();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.injective.insurance.v1beta1.InsuranceFund.serializeBinaryToWriter
    );
  }
};


/**
 * optional InsuranceFund fund = 1;
 * @return {?proto.injective.insurance.v1beta1.InsuranceFund}
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.prototype.getFund = function() {
  return /** @type{?proto.injective.insurance.v1beta1.InsuranceFund} */ (
    jspb.Message.getWrapperField(this, proto.injective.insurance.v1beta1.InsuranceFund, 1));
};


/**
 * @param {?proto.injective.insurance.v1beta1.InsuranceFund|undefined} value
 * @return {!proto.injective.insurance.v1beta1.EventInsuranceFundUpdate} returns this
*/
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.prototype.setFund = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.injective.insurance.v1beta1.EventInsuranceFundUpdate} returns this
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.prototype.clearFund = function() {
  return this.setFund(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.injective.insurance.v1beta1.EventInsuranceFundUpdate.prototype.hasFund = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.injective.insurance.v1beta1.EventRequestRedemption.prototype.toObject = function(opt_includeInstance) {
  return proto.injective.insurance.v1beta1.EventRequestRedemption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.injective.insurance.v1beta1.EventRequestRedemption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.EventRequestRedemption.toObject = function(includeInstance, msg) {
  var f, obj = {
    schedule: (f = msg.getSchedule()) && proto.injective.insurance.v1beta1.RedemptionSchedule.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.injective.insurance.v1beta1.EventRequestRedemption}
 */
proto.injective.insurance.v1beta1.EventRequestRedemption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.injective.insurance.v1beta1.EventRequestRedemption;
  return proto.injective.insurance.v1beta1.EventRequestRedemption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.injective.insurance.v1beta1.EventRequestRedemption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.injective.insurance.v1beta1.EventRequestRedemption}
 */
proto.injective.insurance.v1beta1.EventRequestRedemption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.injective.insurance.v1beta1.RedemptionSchedule;
      reader.readMessage(value,proto.injective.insurance.v1beta1.RedemptionSchedule.deserializeBinaryFromReader);
      msg.setSchedule(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.injective.insurance.v1beta1.EventRequestRedemption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.injective.insurance.v1beta1.EventRequestRedemption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.injective.insurance.v1beta1.EventRequestRedemption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.EventRequestRedemption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSchedule();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.injective.insurance.v1beta1.RedemptionSchedule.serializeBinaryToWriter
    );
  }
};


/**
 * optional RedemptionSchedule schedule = 1;
 * @return {?proto.injective.insurance.v1beta1.RedemptionSchedule}
 */
proto.injective.insurance.v1beta1.EventRequestRedemption.prototype.getSchedule = function() {
  return /** @type{?proto.injective.insurance.v1beta1.RedemptionSchedule} */ (
    jspb.Message.getWrapperField(this, proto.injective.insurance.v1beta1.RedemptionSchedule, 1));
};


/**
 * @param {?proto.injective.insurance.v1beta1.RedemptionSchedule|undefined} value
 * @return {!proto.injective.insurance.v1beta1.EventRequestRedemption} returns this
*/
proto.injective.insurance.v1beta1.EventRequestRedemption.prototype.setSchedule = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.injective.insurance.v1beta1.EventRequestRedemption} returns this
 */
proto.injective.insurance.v1beta1.EventRequestRedemption.prototype.clearSchedule = function() {
  return this.setSchedule(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.injective.insurance.v1beta1.EventRequestRedemption.prototype.hasSchedule = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.toObject = function(opt_includeInstance) {
  return proto.injective.insurance.v1beta1.EventWithdrawRedemption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.injective.insurance.v1beta1.EventWithdrawRedemption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.toObject = function(includeInstance, msg) {
  var f, obj = {
    schedule: (f = msg.getSchedule()) && proto.injective.insurance.v1beta1.RedemptionSchedule.toObject(includeInstance, f),
    redeemCoin: (f = msg.getRedeemCoin()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.injective.insurance.v1beta1.EventWithdrawRedemption}
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.injective.insurance.v1beta1.EventWithdrawRedemption;
  return proto.injective.insurance.v1beta1.EventWithdrawRedemption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.injective.insurance.v1beta1.EventWithdrawRedemption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.injective.insurance.v1beta1.EventWithdrawRedemption}
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.injective.insurance.v1beta1.RedemptionSchedule;
      reader.readMessage(value,proto.injective.insurance.v1beta1.RedemptionSchedule.deserializeBinaryFromReader);
      msg.setSchedule(value);
      break;
    case 2:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setRedeemCoin(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.injective.insurance.v1beta1.EventWithdrawRedemption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.injective.insurance.v1beta1.EventWithdrawRedemption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSchedule();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.injective.insurance.v1beta1.RedemptionSchedule.serializeBinaryToWriter
    );
  }
  f = message.getRedeemCoin();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
};


/**
 * optional RedemptionSchedule schedule = 1;
 * @return {?proto.injective.insurance.v1beta1.RedemptionSchedule}
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.getSchedule = function() {
  return /** @type{?proto.injective.insurance.v1beta1.RedemptionSchedule} */ (
    jspb.Message.getWrapperField(this, proto.injective.insurance.v1beta1.RedemptionSchedule, 1));
};


/**
 * @param {?proto.injective.insurance.v1beta1.RedemptionSchedule|undefined} value
 * @return {!proto.injective.insurance.v1beta1.EventWithdrawRedemption} returns this
*/
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.setSchedule = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.injective.insurance.v1beta1.EventWithdrawRedemption} returns this
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.clearSchedule = function() {
  return this.setSchedule(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.hasSchedule = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cosmos.base.v1beta1.Coin redeem_coin = 2;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.getRedeemCoin = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 2));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.injective.insurance.v1beta1.EventWithdrawRedemption} returns this
*/
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.setRedeemCoin = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.injective.insurance.v1beta1.EventWithdrawRedemption} returns this
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.clearRedeemCoin = function() {
  return this.setRedeemCoin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.injective.insurance.v1beta1.EventWithdrawRedemption.prototype.hasRedeemCoin = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.injective.insurance.v1beta1);
